name: news_application
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cached_network_image: ^3.4.1
  date_format: ^2.0.9
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.5.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  webview_flutter: ^4.4.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/imgs/
    - assets/icons/
